gateway {
  port = 1900

  telemetryEnabled = true
  otelEnabled = true
  otelCollectorEndpoint = "http://127.0.0.1:4317"

  providers {
    gemini {
      model = ["gemini-2.5-flash", "gemini-3-flash-preview" ]
      baseUrl = "https://europe-west1-aiplatform.googleapis.com/v1/projects/cn2526-t2-g01/locations/europe-west1/publishers/google"
    }
  }
}

