gateway {
  port = 1900

  providers {
    openai {
      model = "llama-3.3-70b-versatile"
      baseUrl = "https://api.groq.com/openai/v1"
    }

    gemini {
      model = "gemini-2.5-flash"
      baseUrl = "https://generativelanguage.googleapis.com/v1beta"
    }

    anthropic {
      model = "claude-3-7-sonnet-latest"
      baseUrl = "https://api.anthropic.com/v1"
    }
  }
}

