###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -X POST
#  -d '{
#    "contents": [
#      {
#        "parts": [
#          {
#            "text": "How does AI work?"
#          }
#        ]
#      }
#    ]
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "How does AI work?"
        }
      ]
    }
  ]
}

###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -X POST
#  -d '{
#    "contents": [
#      {
#        "parts": [
#          {
#            "text": "How does AI work?"
#          }
#        ]
#      }
#    ],
#    "generationConfig": {
#      "thinkingConfig": {
#        "thinkingLevel": "low"
#      }
#    }
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "How does AI work?"
        }
      ]
    }
  ],
  "generationConfig": {
    "thinkingConfig": {
      "thinkingLevel": "low"
    }
  }
}

###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -d '{
#    "system_instruction": {
#      "parts": [
#        {
#          "text": "You are a cat. Your name is Neko."
#        }
#      ]
#    },
#    "contents": [
#      {
#        "parts": [
#          {
#            "text": "Hello there"
#          }
#        ]
#      }
#    ]
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "system_instruction": {
    "parts": [
      {
        "text": "You are a cat. Your name is Neko."
      }
    ]
  },
  "contents": [
    {
      "parts": [
        {
          "text": "Hello there"
        }
      ]
    }
  ]
}

###

# curl https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -X POST
#  -d '{
#    "contents": [
#      {
#        "parts": [
#          {
#            "text": "Explain how AI works"
#          }
#        ]
#      }
#    ],
#    "generationConfig": {
#      "stopSequences": [
#        "Title"
#      ],
#      "temperature": 1.0,
#      "topP": 0.8,
#      "topK": 10
#    }
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Explain how AI works"
        }
      ]
    }
  ],
  "generationConfig": {
    "stopSequences": [
      "Title"
    ],
    "temperature": 1.0,
    "topP": 0.8,
    "topK": 10
  }
}

###

POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:streamGenerateContent?alt=sse&key={{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Explain how AI works"
        }
      ]
    }
  ]
}

###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "Schedule a meeting with Bob and Alice for 03/27/2025 at 10:00 AM about the Q3 planning."
        }
      ]
    }
  ],
  "tools": [
    {
      "functionDeclarations": [
        {
          "name": "schedule_meeting",
          "description": "Schedules a meeting with specified attendees at a given time and date.",
          "parameters": {
            "type": "object",
            "properties": {
              "attendees": {
                "type": "array",
                "items": { "type": "string" },
                "description": "List of people attending the meeting."
              },
              "date": {
                "type": "string",
                "description": "Date of the meeting (e.g., '2024-07-29')"
              },
              "time": {
                "type": "string",
                "description": "Time of the meeting (e.g., '15:00')"
              },
              "topic": {
                "type": "string",
                "description": "The subject or topic of the meeting."
              }
            },
            "required": ["attendees", "date", "time", "topic"]
          }
        }
      ]
    }
  ]
}

###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent"
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -X POST
#  -d '{
#    "contents": [{
#      "parts": [{"text": "Search for all details for the latest Euro."}]
#    }],
#    "tools": [
#      {"googleSearch": {}},
#      {"urlContext": {}}
#    ],
#    "generationConfig": {
#        "responseMimeType": "application/json",
#        "responseJsonSchema": {
#            "type": "object",
#            "properties": {
#                "winner": {"type": "string", "description": "The name of the winner."},
#                "final_match_score": {"type": "string", "description": "The final score."},
#                "scorers": {
#                    "type": "array",
#                    "items": {"type": "string"},
#                    "description": "The name of the scorer."
#                }
#            },
#            "required": ["winner", "final_match_score", "scorers"]
#        }
#    }
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Search for all details for the latest Euro."
        }
      ]
    }
  ],
  "tools": [
    {
      "googleSearch": {}
    },
    {
      "urlContext": {}
    }
  ],
  "generationConfig": {
    "responseMimeType": "application/json",
    "responseJsonSchema": {
      "type": "object",
      "properties": {
        "winner": {
          "type": "string",
          "description": "The name of the winner."
        },
        "final_match_score": {
          "type": "string",
          "description": "The final score."
        },
        "scorers": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The name of the scorer."
        }
      },
      "required": [
        "winner",
        "final_match_score",
        "scorers"
      ]
    }
  }
}

###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
#-H 'Content-Type: application/json'
#-H "x-goog-api-key: $GEMINI_API_KEY"
#-d '{
#  "systemInstruction": {
#    "parts": [
#      {
#        "text": "És um pirata sarcástico e resmungão. Responde sempre usando calão de pirata e queixa-te da falta de rum."
#      }
#    ]
#  },
#  "contents": [
#    {
#      "parts": [
#        {
#          "text": "Podes explicar-me como funciona a internet?"
#        }
#      ]
#    }
#  ]
#}'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "systemInstruction": {
    "parts": [
      {
        "text": "És um pirata sarcástico e resmungão. Responde sempre usando calão de pirata e queixa-te da falta de rum."
      }
    ]
  },
  "contents": [
    {
      "parts": [
        {
          "text": "Podes explicar-me como funciona a internet?"
        }
      ]
    }
  ]
}

###

# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
#-H 'Content-Type: application/json'
#-H "x-goog-api-key: $GEMINI_API_KEY"
#-d '{
#  "contents": [
#    {
#      "parts": [
#        {
#          "text": "Como está o tempo em Lisboa hoje?"
#        }
#      ]
#    }
#  ],
#  "tools": [
#    {
#      "functionDeclarations": [
#        {
#          "name": "obter_meteorologia",
#          "description": "Obtém a meteorologia atual para uma determinada cidade.",
#          "parameters": {
#            "type": "OBJECT",
#            "properties": {
#              "cidade": {
#                "type": "STRING",
#                "description": "A cidade para a qual queremos a meteorologia."
#              }
#            },
#            "required": ["cidade"]
#          }
#        }
#      ]
#    }
#  ],
#  "toolConfig": {
#    "functionCallingConfig": {
#      "mode": "ANY",
#      "allowedFunctionNames": ["obter_meteorologia"]
#    }
#  }
#}'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Como está o tempo em Lisboa hoje?"
        }
      ]
    }
  ],
  "tools": [
    {
      "functionDeclarations": [
        {
          "name": "obter_meteorologia",
          "description": "Obtém a meteorologia atual para uma determinada cidade.",
          "parameters": {
            "type": "OBJECT",
            "properties": {
              "cidade": {
                "type": "STRING",
                "description": "A cidade para a qual queremos a meteorologia."
              }
            },
            "required": [
              "cidade"
            ]
          }
        }
      ]
    }
  ],
  "toolConfig": {
    "functionCallingConfig": {
      "mode": "ANY",
      "allowedFunctionNames": [
        "obter_meteorologia"
      ]
    }
  }
}

###

POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "Descreve o que vês nesta imagem e diz-me se a planta precisa de água."
        },
        {
          "inlineData": {
            "mimeType": "image/jpeg",
            "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
          }
        }
      ]
    }
  ]
}

###

POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        { "text": "Como está o tempo em Lisboa hoje?" }
      ]
    },
    {
      "role": "model",
      "parts": [
        {
          "functionCall": {
            "name": "obter_meteorologia",
            "args": { "cidade": "Lisboa" }
          }
        }
      ]
    },
    {
      "role": "user",
      "parts": [
        {
          "functionResponse": {
            "name": "obter_meteorologia",
            "response": {
              "temperatura_celsius": 22,
              "condicao": "Céu limpo",
              "vento_kmh": 15
            }
          }
        }
      ]
    }
  ]
}

###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent
x-goog-api-key: {{GEMINI_API_KEY}}
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Quantos r's tem a palavra 'morango'?"
        }
      ]
    }
  ],
  "generationConfig": {
    "thinkingConfig": {
      "includeThoughts": true
    }
  }
}



